
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: futebol
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  node-app:
    build: .
    container_name: node-app
    depends_on:
      - mysql-server
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    env_file:
      - .env
    command: npm run start
    restart: always

volumes:
  db_data:
    driver: local
